# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77dce3c44ed43a43e97a893acb0bae9bb0607cb2f737e8424bf9df69f3a90eb3a5ed90e1bfbf3c1c13adf9d47e6555386e0e0f73dd71ae5957fc1b5d91e3bf81

test:
  secret_key_base: 1b042a3606336abd239d1a9831f5c1120c7324c07698cb09a2a09cf825034af47951ffeabee1057583d85a3b5c0bbda375a59aeaad8da0539abc2d71b5aaf46b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
